.travis.yml

As there are not real build tasks yet, we'll need an empty task to keep
Travis from using its default task (which would break the build).

[BUGFIX] Get the Travis builds green

---

composer.json

We don't need minimum-stability: dev as the phpList core dependency
already explicitly is marked as unstable.
This will make the composer updates much faster.

[TASK] Use stable dependencies

---

.travis.yml

This is required to fix the build as the database structure that is going
to be imported is only available after the composer install.

[BUGFIX] Import the database after the composer install

---

.travis.yml

Now the build will run both on the Trusty as well as the Precise images.

[BUGFIX] Fix MySQL with the new Trusty Travis images

---

Classes/Controller/SessionController.php
Documentation/Api/RestApi.apib
Tests/Integration/Controller/SessionControllerTest.php

Now the status code correctly signifies that the problem is with the data
provided by the client, not some problem on the server side.

[BUGFIX] Return HTTP status 400 on bad client data instead of 500

---

.gitignore
Tests/Integration/Composer/ScriptsTest.php
composer.json

Note: The console will only be added if this project is the project root
(i.e., usually when developing the package), not if is a requirement of
the base-distribution package (or any other package).

[FEATURE] Add the Symfony console and the public web/ directory

---

Configuration/bundles.yml

This is to ensure the application keeps working as long as the file is
not autogenerated.

[TASK] Add a bundle configuration file

---

Classes/Controller/SessionController.php
Tests/Integration/Composer/ScriptsTest.php
composer.json

This will reduce the amount of configuration needed in the composer.json.

[CLEANUP] Use annotations to define the routes

---

composer.json

For the automatic cache creation to also work on Mac OS (in addition
to Linux), the setting needs to be changed.

[BUGFIX] Fix the symfony-app-dir setting in the composer.json

---

.travis.yml

There was a double set of single quotes for the host name,
and the user name was not quoted at all.

[BUGFIX] Fix SQL GRANT syntax in .travis.yml

---

Classes/Controller/SessionController.php
Tests/Integration/Controller/SessionControllerTest.php

FOSRestBundle requires the correct content type. So the tests need to
provide it, and the controller needs to verify it.
Also drop an unnecessary pair of parenthesis from the test.

[BUGFIX] Provide a request content type in the integration tests

---

Tests/Integration/Controller/SessionControllerTest.php
composer.json

The application/json content type should only be used for routes
that are part of our REST API.

[BUGFIX] Keep text/html as content-type for non-REST routes

---

Tests/Integration/Controller/Fixtures/Administrator.csv

This is necessary for the tests to pass once we allow only super users
to authenticate.

[BUGFIX] Make the admin in the tests a super user

---

Documentation/Api/RestApi.apib
README.md

- document that only superuser admins can use the REST API
- document that the REST APIs of v4 and v3 should not be used in
parallel on the same database
- change the future tense to the present tense (as there now are some
working REST actions)
Fixes #64

[TASK] Improve the README

---

Classes/Controller/SessionController.php
Documentation/Api/RestApi.apib
Tests/Integration/Controller/SessionControllerTest.php

This makes the request naming schema consistent with the response naming
schema.

[TASK] Use snake_case for the JSON request parameter keys

---

Tests/Integration/Controller/AbstractControllerTest.php

This makes the JSON representation of dates independent of the test
machine's PHP time zone.

[BUGFIX] Use "UTC" as time zone in the integration tests

---

.travis.yml

The dependencies provide the SQL file that will be used for the DB import.
So this order is necessary for the build to pass reliably.

[BUGFIX] Install dependencies before importing the DB

---

.github/CONTRIBUTING.md

This enables syntax highlighting when rendering markdown.

[TASK] Provide the code language in markdown files

---

Tests/Integration/Controller/ListControllerTest.php

The tests for access checks for cases where the list does not exist
will follow in separate commits.

[BUGFIX] Create list before access check integration test

---

Tests/Integration/Composer/ScriptsTest.php
Tests/Integration/Controller/AbstractControllerTest.php
Tests/Integration/Controller/ListControllerTest.php
Tests/Integration/Controller/SessionControllerTest.php
Tests/Integration/Controller/SubscriberControllerTest.php
Tests/Integration/Routing/RoutingTest.php
Tests/System/Controller/SessionControllerTest.php
Tests/Unit/PhpListRestBundleTest.php

This will allow for subclasses to overwrite methods and constants and hence
is the current recommended practice.

[TASK] Use static:: instead of self::

---

.gitignore
CHANGELOG.md
composer.json
tests/Integration/Composer/ScriptsTest.php

This will bring the project closer to the default Symfony
project structure.

[CLEANUP] Rename web/ to public/

---

composer.json

Composer tries to install doctrine/instantiator 1.1.0 on PHP 7.0,
but this version requires PHP ^7.1. This seems to be a bug in Composer,
and requiring the latest PHP-7.0-compatible version of
phpunit/phpunit-mock-objects works around this issue.

[BUGFIX] Fix Composer-related build failure with PHP 7.0

---

.travis.yml
CHANGELOG.md
README.md
composer.json

The core package has been renamed. So the dependencies need to be updated.

[TASK] Use the renamed phplist/core package

---

CHANGELOG.md
composer.json

sensio/framework-extra-bundle 5.1.1 has renamed some services.
friendsofsymfony/rest-bundle has not yet caught up with the new service
IDs, causing all REST routes to break. To work around this until
friendsofsymfony/rest-bundle has fixed this, sensio/framework-extra-bundle
is pinned to version 5.1.0.
This is the corresponding bug report:
https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1878

[BUGFIX] Pin sensio/framework-extra-bundle at 5.1.0

---

composer.json

Signed-off-by: Xheni Myrtaj <myrtajxheni@gmail.com>
fosRest bundle filters the messages as they may contain sensitive content but in our case, we want to display messages such as: incomplete credentials.
Fix #109

Whitelist BadRequestHttpException so that messages are not sanitized

---

composer.json
config/services.yml
src/ViewHandler/SecuredViewHandler.php
tests/System/Controller/SecuredViewHandlerTest.php

Added security headers such as:
```
'X-Content-Type-Options' =>'nosniff',
'Content-Security-Policy' => "default-src 'none'",
'X-Frame-Options' => 'DENY'
```
Fix #111

Add security headers to the default response 

---

src/Controller/ListController.php
tests/Integration/Controller/AbstractControllerTest.php
tests/Integration/Controller/Fixtures/SubscriberList.csv
tests/Integration/Controller/ListControllerTest.php

[FEATURE] Get the number of subscribers of list and added tests  

---

tests/Integration/Controller/ListControllerTest.php

The expected number of subscribers for listid=2 is actually 2
https://github.com/phpList/rest-api/blob/master/tests/Integration/Controller/Fixtures/Subscription.csv

Change the expected subscribers count to fix the test 

---

.github/CONTRIBUTING.md
.github/workflows/restapi-docs.yml
.gitignore
composer.json
src/Controller/ListController.php
src/Controller/SubscriberController.php

Signed-off-by: fenn-cs <fenn25.fn@gmail.com>
This PR introduces automatic deployment for automatically generated `OPENAPI` spefication to @phpList/restapi-docs.
Rundown 
---
- Clone `phplist/resp-api` (phplist api source)
- Run swagger and generate `OPENAPI specification
- Save generated specification
- Clone `phplist/restapi-docs`(swagger ui)
- Compared generated specification against existing specification in `restapid-docs` for differences
- If any differences, commit and push for automatic deployment.

Implemented auto generate and deploy restapi-doc action

---

.github/workflows/restapi-docs.yml

Fix restapi-docs file location

Fix restapi-docs file location

---

config/services/services.yml
src/Common/Service/Provider/PaginatedDataProvider.php
src/Subscription/Controller/SubscriberController.php
src/Subscription/OpenApi/SwaggerSchemasResponse.php
src/Subscription/Serializer/SubscriberHistoryNormalizer.php
src/Subscription/Service/SubscriberHistoryService.php
src/Subscription/Service/SubscriberService.php

- endpoint to return subscriber history (with filter options)
Are your changes covered with unit tests, and do they not break anything?
You can run the existing unit tests using this command:
vendor/bin/phpunit tests/
Have you checked that you code is well-documented and follows the PSR-2 coding
style?
You can check for this using this command:
vendor/bin/phpcs --standard=PSR2 src/ tests/
If there's anything else that's important and relevant to your pull
request, mention that information here. This could include benchmarks,
or other information.
If you are updating any of the CHANGELOG files or are asked to update the
CHANGELOG files by reviewers, please add the CHANGELOG entry at the top of the file.
Thanks for contributing to phpList!

Subscriber history endpoint

---

config/services/managers.yml
src/Identity/Controller/PasswordResetController.php
src/Identity/Request/RequestPasswordResetRequest.php
src/Identity/Request/ResetPasswordRequest.php
src/Identity/Request/ValidateTokenRequest.php
tests/Integration/Identity/Controller/PasswordResetControllerTest.php
tests/Unit/Identity/Request/RequestPasswordResetRequestTest.php
tests/Unit/Identity/Request/ResetPasswordRequestTest.php
tests/Unit/Identity/Request/ValidateTokenRequestTest.php

- Add endpoints for password reset
Are your changes covered with unit tests, and do they not break anything?
You can run the existing unit tests using this command:
vendor/bin/phpunit tests/
Have you checked that you code is well-documented and follows the PSR-2 coding
style?
You can check for this using this command:
vendor/bin/phpcs --standard=PSR2 src/ tests/
If there's anything else that's important and relevant to your pull
request, mention that information here. This could include benchmarks,
or other information.
If you are updating any of the CHANGELOG files or are asked to update the
CHANGELOG files by reviewers, please add the CHANGELOG entry at the top of the file.
Thanks for contributing to phpList!

Password reset
